// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiew9q56HUJFPS9JLnShclvWMSkjfHM4M',
    appId: '1:465693244665:web:34a7aefe4431b17d1e7628',
    messagingSenderId: '465693244665',
    projectId: 'providerlogin-f0ff7',
    authDomain: 'providerlogin-f0ff7.firebaseapp.com',
    storageBucket: 'providerlogin-f0ff7.firebasestorage.app',
    measurementId: 'G-G6SN8G8RNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bhsdxpEiMXWWfeQ0WuAGBeXO_w_yEi4',
    appId: '1:465693244665:android:8a1134b0362d59461e7628',
    messagingSenderId: '465693244665',
    projectId: 'providerlogin-f0ff7',
    storageBucket: 'providerlogin-f0ff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkn-s3wApPtz20hcQUKIO-1YGUmhFFwg',
    appId: '1:465693244665:ios:0613de47a90289b91e7628',
    messagingSenderId: '465693244665',
    projectId: 'providerlogin-f0ff7',
    storageBucket: 'providerlogin-f0ff7.firebasestorage.app',
    iosBundleId: 'com.example.providerLogin',
  );
}
